import { CharStream, CommonTokenStream } from 'antlr4ng';

import { GeoTortueLexer } from '@infrastructure/antlr/generated/GeoTortueLexer';
import { GeoTortueParser } from '@infrastructure/antlr/generated/GeoTortueParser';
import * as GTNParser from '@infrastructure/antlr/generated/GeoTortueParser';

// Domain & Infrastructure
import { GTNContainer } from '@infrastructure/di/GTNContainer';
import { GTN_TYPES } from '@infrastructure/di/GTNTypes';
import type { IGTNTurtleRepository } from '@domain/interfaces/IGTNTurtleRepository';
import type { IGTNMathEvaluator } from '@domain/interfaces/IGTNMathEvaluator';
import type { IGTNLanguageService } from '@domain/interfaces/IGTNLanguageService';
import type { IGTNLogger } from '@app/interfaces/IGTNLogger';

import { GTNExecutionVisitor } from './GTNExecutionVisitor';
import type { GTNTurtle } from '@domain/entities/GTNTurtle';
import type { IGTNProcedureRegistry } from '@domain/interfaces/IGTNProcedureRegistry';

function parse(code: string): GTNParser.ProgramContext;
function parse(code: string, rule: 'program'): GTNParser.ProgramContext;
function parse(code: string, rule: 'statement'): GTNParser.StatementContext;

// Helper function to quickly generate an ANTLR ParseTree from a string
function parse(code: string, rule: 'program' | 'statement' = 'program') {
  const chars = CharStream.fromString(code);
  const lexer = new GeoTortueLexer(chars);
  const tokens = new CommonTokenStream(lexer);
  const parser = new GeoTortueParser(tokens);

  // Suppress console errors during testing
  parser.removeErrorListeners();

  return rule === 'program' ? parser.program() : parser.statement();
}

describe('GTNExecutionVisitor', () => {
  let visitor: GTNExecutionVisitor;

  // Mocks
  let mockRepo: IGTNTurtleRepository;
  let mockTurtle: GTNTurtle;
  let mockMath: IGTNMathEvaluator;
  let mockLogger: IGTNLogger;
  let mockLangService: IGTNLanguageService;
  let mockRegistry: IGTNProcedureRegistry;

  beforeEach(() => {
    // Enable fake timers to bypass the 1000ms delay in tick()
    vi.useFakeTimers();

    // 1. Clear Container
    const container = GTNContainer.getInstance();
    container.clear();

    // 1. Mock Logger
    container.registerSingleton(GTN_TYPES.Logger, () => ({
      info: vi.fn(),
      warn: vi.fn(),
      error: vi.fn(),
      debug: vi.fn()
    }));

    // 2. Mock Math Evaluator
    const mockMathEvaluator: IGTNMathEvaluator = {
      evaluate: vi.fn((expr: string) => {
        const num = parseFloat(expr);
        return isNaN(num) ? expr : num;
      })
    } as unknown as IGTNMathEvaluator;
    container.registerSingleton(GTN_TYPES.MathEvaluator, () => mockMathEvaluator);

    // 3. Mock Language Service
    // const mockLangService: IGTNLanguageService = {
    //   getCssColor: vi.fn((color: string) => color.toLowerCase())
    // } as unknown as IGTNLanguageService;
    container.registerSingleton(GTN_TYPES.LanguageService, () => mockLangService);

    // 4. ✅ Mock Procedure Registry (Fixes the DI Error!)
    const fakeRegistryStore = new Map();
    mockRegistry = {
      // save context generated by ANTLR in a Map of test
      register: vi.fn((name, ctx) => fakeRegistryStore.set(name, ctx)),
      // to be returned when asked by visitor
      getProcedure: vi.fn((name) => fakeRegistryStore.get(name)),
      getAllNames: vi.fn(() => Array.from(fakeRegistryStore.keys())),
      clear: vi.fn(() => fakeRegistryStore.clear())
    } as unknown as IGTNProcedureRegistry;
    container.registerSingleton(GTN_TYPES.ProcedureRegistry, () => mockRegistry);

    // 5. Mock Turtle & Repository
    mockTurtle = {
      forward: vi.fn(),
      backward: vi.fn(),
      right: vi.fn(),
      left: vi.fn(),
      setPenColor: vi.fn(),
      setPenSize: vi.fn(),
      penUp: vi.fn(),
      penDown: vi.fn(),
      state: {
        position: { x: 0, y: 0, z: 0 } //,
        // rotation: { x: 0, y: 0, z: 0, w: 1 }
      },
      isVisible: true
    } as unknown as GTNTurtle;

    mockRepo = {
      getAll: vi.fn().mockReturnValue([mockTurtle]),
      reset: vi.fn(),
      clearAllLines: vi.fn(),
      clear: vi.fn()
    } as unknown as IGTNTurtleRepository;

    // 3. Setup Mock Math Evaluator
    mockMath = {
      isExpression: vi.fn().mockReturnValue(true),
      // Accepts 3 args to match Visitor call signature (expr, scope, mode)
      evaluate: vi.fn((expr: string, scope?: any, _mode?: any) => {
        // Simple mock logic: return parsed float or handle variables passed in scope
        const num = parseFloat(expr);
        if (!isNaN(num)) {
          return num;
        }

        // Return variable from scope if exists
        if (scope && Object.hasOwn(scope, expr)) {
          return scope[expr];
        }

        // Return string literal if quotes (for colors)
        if (expr.startsWith('"') || expr.startsWith("'")) {
          return expr.replace(/['"]/g, '');
        }

        // Throw for undefined variables (needed for Fallback Strategy test)
        if (expr === 'UNKNOWN_VAR') {
          throw new Error('Undefined symbol UNKNOWN_VAR');
        }

        return expr; // Return as string
      })
    } as unknown as IGTNMathEvaluator;

    // 4. Setup Logger
    mockLogger = {
      warn: vi.fn(),
      error: vi.fn(),
      info: vi.fn(),
      debug: vi.fn()
    } as unknown as IGTNLogger;

    // 5. Setup Language Service
    mockLangService = {
      getCssColor: vi.fn((name) => {
        const map: any = { rouge: 'red', bleu: 'blue' };
        return map[name];
      })
      //, getInternalKeyword: vi.fn()
    } as unknown as IGTNLanguageService;

    // 6. Register Mocks BEFORE instantiating Visitor
    container.registerInstance(GTN_TYPES.Logger, mockLogger);
    container.registerInstance(GTN_TYPES.MathEvaluator, mockMath);
    container.registerInstance(GTN_TYPES.LanguageService, mockLangService);

    // 6. Instantiate Visitor (it will resolve dependencies now)
    visitor = new GTNExecutionVisitor(mockRepo);
    // Optional: override the tick delay for tests to run instantly
    // @ts-ignore - Accessing private property for testing speed
    visitor.stepDelayMs = 0;

    // Mock 'tick' to resolve immediately so we don't need to wait 1s per step
    // This makes the tests fast and removes the "Non-Promise" linter issues
    vi.spyOn(visitor as any, 'tick').mockResolvedValue(undefined);
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  // --- Movement Tests ---

  it('should execute move forward (GT_FORWARD)', async () => {
    const tree = parse('GT_FORWARD 100', 'program');
    await (visitor.visitProgram(tree) as Promise<any>);

    expect(mockTurtle.forward).toHaveBeenCalledWith(100);
  });

  it('should execute move backward (GT_BACKWARD)', async () => {
    const tree = parse('GT_BACKWARD 50', 'program');
    await (visitor.visitProgram(tree) as Promise<any>);

    expect(mockTurtle.backward).toHaveBeenCalledWith(50);
  });

  it('should execute turn tight (GT_TURN_RIGHT)', async () => {
    const tree = parse('GT_TURN_RIGHT 90', 'program');
    await (visitor.visitProgram(tree) as Promise<any>);

    // Visitor converts to degrees. Assuming logic is direct for this test.
    // If toDegree does conversion, check that value.
    // Here we assume input 90 stays 90 based on standard impl.
    expect(mockTurtle.right).toHaveBeenCalledWith(90);
  });

  // --- Logic & Control Flow ---

  it('should handle Assignments and Variables in single program', async () => {
    // Run in ONE program string so scope persists
    const code = 'x := 42; GT_FORWARD x;';
    const tree = parse(code);
    await (visitor.visitProgram(tree) as Promise<any>);

    expect(mockTurtle.forward).toHaveBeenCalledWith(42);
  });

  it('should execute repeat loop (GT_REPEAT)', async () => {
    const tree = parse('GT_REPEAT 3 [ GT_FORWARD 10; ]', 'program');
    await (visitor.visitProgram(tree) as Promise<any>);

    expect(mockTurtle.forward).toHaveBeenCalledTimes(3);
    expect(mockTurtle.forward).toHaveBeenCalledWith(10);
  });

  it('should execute if bock (GT_IF)', async () => {
    // Mock math to return true/false
    vi.mocked(mockMath.evaluate).mockImplementationOnce(() => true);
    const tree = parse('GT_IF 1 [ GT_FORWARD 10 ]', 'program');
    await (visitor.visitProgram(tree) as Promise<any>);
    expect(mockTurtle.forward).toHaveBeenCalledWith(10);
  });

  // --- Color Logic (Critical) ---

  describe('visitSetColor', () => {
    const CMD = 'GT_PEN_COLOR';
    it('Strategy 1: Direct String Literal (GT_PEN_COLOR "rouge")', async () => {
      const tree = parse(`${CMD} "rouge"`, 'program');
      await (visitor.visitProgram(tree) as Promise<any>);

      // Should bypass math evaluator for literals
      // resolveCssColor strips quotes -> "rouge" -> langService -> "red"
      expect(mockTurtle.setPenColor).toHaveBeenCalledWith('red');
    });

    it('Strategy 2: Variable Evaluation (GT_PEN_COLOR x)', async () => {
      // Use assignment command to define variable naturally.
      // 1. Assign "bleu" to x. (Quotes needed for string literal).
      // 2. Use x in color command.
      // (visitor as any).scopes[0]!['x'] = 'bleu';
      const code = `x := "bleu"; ${CMD} x;`;

      // 2. Parse as STATEMENT to avoid visiting Program (which resets scopes)
      const tree = parse(code);
      await (visitor.visitProgram(tree) as Promise<any>);

      // Verify Steps
      // 1. Math eval should have been called for 'x'
      expect(mockMath.evaluate).toHaveBeenCalled();

      // 2. LangService should have been called to translate 'bleu' ---> 'blue'
      expect(mockLangService.getCssColor).toHaveBeenCalledWith('bleu');

      // 3. Turtle should receive 'blue'
      expect(mockTurtle.setPenColor).toHaveBeenCalledWith('blue');
    });

    it('Strategy 3: Fallback (GT_PEN_COLOR rouge - no quotes)', async () => {
      // Math.js ne reconnait pas la variable nommé rouge et émet en conséquence une exception
      // Elle est capturé par visitSetColor car elle correspond au pattern 'Undefined symbol'
      // afin de retourner "rouge" comme couleur
      // avec alors la recherche de la couleur css correspondante

      // Math evaluator throws "Undefined symbol", Visitor catches and treats rouge as literal "rouge"
      vi.mocked(mockMath.evaluate).mockImplementation(() => {
        throw new Error('Undefined symbol rouge');
      });

      const tree = parse(`${CMD} rouge`);
      await (visitor.visitProgram(tree) as Promise<any>);

      expect(mockLogger.warn).toHaveBeenCalledWith(
        expect.stringContaining('Treating as color literal')
      );
      expect(mockTurtle.setPenColor).toHaveBeenCalledWith('red');
    });

    it('should ignore invalid colors', async () => {
      // "invalid_color" returns undefined from LangService, resolveCssColor returns input
      // isCssColor checks if it is valid.
      // Assuming isCssColor('invalid_color') returns false.

      const tree = parse('GT_PEN_COLOR "prout"', 'program');
      await (visitor.visitProgram(tree) as Promise<any>);

      expect(mockTurtle.setPenColor).not.toHaveBeenCalled();
    });
  });

  // --- Procedures ---

  it('should define and call a user function', async () => {
    // Current Grammar: GT_FUNCTION_DEF identifier (...) := expr
    // It does not support procedure blocks (commands) yet.
    // We test a math function: double(x) := x * 2

    // 1. Define
    const defCode = 'GT_FUNCTION_DEF double (x) := x * 2';
    await (visitor.visitProgram(parse(defCode, 'program')) as Promise<any>);

    // 2. Call (Use it in a movement command to verify result)
    // mockMath needs to handle the calculation since Visitor delegates expression eval to it.
    // However, Visitor handles the scope push/pop.

    // We mock the evaluate to simulate the math engine returning 100 for "x * 2" where x=50
    vi.mocked(mockMath.evaluate).mockImplementation((expr, scope) => {
      if (expr === 'x * 2' && scope?.x === 50) return 100; // Simulate function body exec
      if (expr === 'double(50)') return 100; // Simulate main call
      return 50;
    });

    // We can't easily test the full engine integration without a real MathEvaluator,
    // but we can check if the definition was stored.
    expect(visitor['userFunctions'].has('double')).toBe(true);
  });

  it('should warn on unknown procedure call', async () => {
    // unknownFunc is interpreted as a ProcedureCall (identifier expr*)
    const tree = parse('unknownFunc 10', 'program');

    await (visitor.visitProgram(tree) as Promise<any>);

    // FUTURE the warning message should return the original name of the function
    expect(mockLogger.warn).toHaveBeenCalledWith(
      '[Visitor] ❌ Unknown procedure or function: unknownFunc'
    );
  });

  it('should register a procedure definition into the registry', async () => {
    const tree = parse('GT_PROCEDURE_START CARRE GT_REPEAT 4 [ GT_FORWARD 50; ] GT_PROCEDURE_END');
    await visitor.visitProgram(tree);

    // The visitor should have called register on our mocked registry
    expect(mockRegistry.register).toHaveBeenCalledTimes(1);
    expect(mockRegistry.register).toHaveBeenCalledWith('carre', expect.anything());
  });

  it('should execute a procedure call from the registry', async () => {
    // 1. Provide the definition du the visitor
    // The visitor then will extract the ProcedureDefinitionContext
    // and call mockRegistry.register() to save it!
    const procTree = parse('GT_PROCEDURE_START CARRE GT_FORWARD 100; GT_PROCEDURE_END');
    await visitor.visitProgram(procTree);

    // check the procedure has been registered
    expect(mockRegistry.getProcedure('carre')).toBeDefined();

    // 2. Create a false context ANTLR
    // to simulate the AST avoiding any parsing error
    const mockCallCtx = {
      GT_IDENTIFIER: () => ({ getText: () => 'CARRE' }),
      commandArgument: () => [] // Aucun argument passé à l'appel
    } as unknown as GTNParser.ProcedureCallStatementContext;

    // 3. Direct call to visitor with the false context
    await visitor.visitProcedureCallStatement(mockCallCtx);

    // 4. Verify it looked up the procedure and executed its body
    expect(mockRegistry.getProcedure).toHaveBeenCalledWith('carre');
    expect(mockTurtle.forward).toHaveBeenCalledWith(100);
  });

  // --- System Commands ---

  it('should handle ClearGraphics (GT_CLEAR_GRAPHICS)', async () => {
    const tree = parse('GT_CLEAR_GRAPHICS', 'program');
    await (visitor.visitProgram(tree) as Promise<any>);

    expect(mockRepo.clearAllLines).toHaveBeenCalled();
  });

  it('should handle reset (GT_RESET)', async () => {
    const tree = parse('GT_RESET', 'program');
    await (visitor.visitProgram(tree) as Promise<any>);

    expect(mockRepo.reset).toHaveBeenCalled();
    // Checks state reset
    expect(mockTurtle.state.position.x).toBe(0);
    expect(mockTurtle.state.position.y).toBe(0);
    expect(mockTurtle.state.position.z).toBe(0);
    // TODO to be completed with rotation
  });

  it('should reset repo on visitProgram', async () => {
    const tree = parse('', 'program');
    await (visitor.visitProgram(tree) as Promise<any>);
    expect(mockRepo.reset).not.toHaveBeenCalled();
  });
});
