/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/generate-command-arities.ts using GeoTortueParser.g4
 *
 * Note: This auto-generated file is intentionally tracked by Git. Do not add it to .gitignore.
 */

/**
 * Arity metadata for a DSL command.
 * - min: minimal number of arguments.
 * - max: maximal number of arguments. If omitted, the command is variadic.
 */
export type GTNCommandArity = {
  min: number;
  max?: number;
};

/**
 * Command arities for primitive DSL commands.
 */
export const GTN_COMMAND_ARITIES: Readonly<Record<string, GTNCommandArity>> = {
  GT_CLEAR_GRAPHICS: { min: 0, max: 0 },
  GT_RESET: { min: 0, max: 0 },
  GT_HIDE_TURTLE: { min: 0, max: 0 },
  GT_SHOW_TURTLE: { min: 0, max: 0 },
  GT_PEN_UP: { min: 0, max: 0 },
  GT_PEN_DOWN: { min: 0, max: 0 },
  GT_COMPASS: { min: 0, max: 0 },
  GT_INIT: { min: 0, max: 0 },
  GT_WAIT: { min: 0, max: 0 },
  GT_STOP: { min: 0, max: 0 },
  GT_UNDO_DRAWING: { min: 0, max: 0 },
  GT_DRAW_POINT: { min: 0, max: 0 },
  GT_MIRROR: { min: 0, max: 0 },
  GT_FORWARD: { min: 1, max: 1 },
  GT_BACKWARD: { min: 1, max: 1 },
  GT_TURN_RIGHT: { min: 1, max: 1 },
  GT_TURN_LEFT: { min: 1, max: 1 },
  GT_PEN_THICKNESS: { min: 1, max: 1 },
  GT_PEN_COLOR: { min: 1, max: 1 },
  GT_AIM: { min: 1, max: 1 },
  GT_MIMIC: { min: 1, max: 1 },
  GT_PAUSE: { min: 1, max: 1 },
  GT_ROLL_UP: { min: 1, max: 1 },
  GT_ROLL_DOWN: { min: 1, max: 1 },
  GT_ROLL_RIGHT: { min: 1, max: 1 },
  GT_ROLL_LEFT: { min: 1, max: 1 },
  GT_ROTATE_XY: { min: 1, max: 1 },
  GT_ROTATE_XZ: { min: 1, max: 1 },
  GT_ROTATE_YZ: { min: 1, max: 1 },
  GT_SNAPSHOT: { min: 1, max: 1 },
  GT_RETURN: { min: 1, max: 1 },
  GT_DRAW_CIRCLE: { min: 1, max: 1 },
  GT_FILL: { min: 1, max: 1 },
  GT_MANIPULATE_GRAPH: { min: 1, max: 1 },
  GT_DRAW_ARC: { min: 2, max: 2 },
  GT_TELEPORT: { min: 0 },
  GT_SELECT: { min: 0 },
  GT_DELETE: { min: 0 },
  GT_DISPLAY: { min: 0 },
  GT_WRITE: { min: 0 },
  GT_SAY: { min: 0 },
  GT_EXECUTE: { min: 0 },
  GT_PLAY: { min: 0 },
  GT_SCORE: { min: 0 },
  GT_CONCERT: { min: 0 },
  GT_ASK_FOR_VALUE: { min: 0 },
  GT_GLOBAL: { min: 0 }
};
