/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/generate-command-arities.ts using GeoTortueParser.g4
 *
 * Note: This auto-generated file is intentionally tracked by Git. Do not add it to .gitignore.
 */

/**
 * Arity metadata for a DSL command.
 * - min: minimal number of arguments.
 * - max: maximal number of arguments. If omitted, the command is variadic.
 */
export type GTNCommandArity = {
  min: number;
  max?: number;
};

/**
 * Command arities for primitive DSL commands.
 */
export const GTN_COMMAND_ARITIES: Readonly<Record<string, GTNCommandArity>> = {
  GT_FORWARD: { min: 1, max: 1 },
  GT_BACKWARD: { min: 1, max: 1 },
  GT_RIGHT: { min: 1, max: 1 },
  GT_LEFT: { min: 1, max: 1 },
  GT_VG: { min: 0, max: 0 },
  GT_RZ: { min: 0, max: 0 },
  GT_HIDE_TURTLE: { min: 0, max: 0 },
  GT_SHOW_TURTLE: { min: 0, max: 0 },
  GT_PEN_UP: { min: 0, max: 0 },
  GT_PEN_DOWN: { min: 0, max: 0 },
  GT_THICKNESS: { min: 1, max: 1 },
  GT_PEN_COLOR: { min: 1, max: 1 },
  GT_FILL: { min: 1, max: 1 },
  GT_PVH: { min: 1, max: 1 },
  GT_PVB: { min: 1, max: 1 },
  GT_PVG: { min: 1, max: 1 },
  GT_PVD: { min: 1, max: 1 },
  GT_VISE: { min: 1, max: 1 },
  GT_TLP: { min: 1 },
  GT_BOUSSOLE: { min: 0, max: 0 },
  GT_MIMIC: { min: 1, max: 1 },
  GT_MIRROR: { min: 0, max: 0 },
  GT_PVXY: { min: 1, max: 1 },
  GT_PVXZ: { min: 1, max: 1 },
  GT_PVYZ: { min: 1, max: 1 },
  GT_WRITE: { min: 1 },
  GT_SAY: { min: 1 },
  GT_SNAPSHOT: { min: 1, max: 1 },
  GT_PAUSE: { min: 1, max: 1 },
  GT_RETURN: { min: 1, max: 1 },
  GT_STOP: { min: 0, max: 0 },
  GT_WAIT: { min: 0, max: 0 },
  GT_CIRCLE: { min: 1, max: 1 },
  GT_ARC: { min: 2, max: 2 },
  GT_POINT: { min: 0, max: 0 },
  GT_GLOBAL: { min: 1 },
  GT_EFF: { min: 1 },
  GT_INIT: { min: 0, max: 0 },
  GT_AFF: { min: 1 },
  GT_MG: { min: 1 },
  GT_PLAY: { min: 1 },
  GT_SCORE: { min: 1 },
  GT_CONCERT: { min: 1 },
  GT_EXECUTE: { min: 1 },
  GT_UNDO: { min: 0, max: 0 },
  GT_ASK_FOR: { min: 1, max: 2 }
};
