/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/generate-antlr-token-enum.ts using GeoTortueParser and GeoTortueLexer
 */

export enum GTNToken {
  GT_REP = 1,
  GT_WHILE = 2,
  GT_IF = 3,
  GT_THEN = 4,
  GT_ELSE = 5,
  GT_FOR_EACH = 6,
  GT_FROM = 7,
  GT_TO = 8,
  GT_IN_LIST = 9,
  GT_FUN = 10,
  GT_ASK_FOR = 11,
  GT_ALL = 12,
  GT_ASSIGN_KEY = 13,
  GT_RESTE = 14,
  GT_BINOM = 15,
  GT_ALEA = 16,
  GT_FORWARD = 17,
  GT_BACKWARD = 18,
  GT_RIGHT = 19,
  GT_LEFT = 20,
  GT_VG = 21,
  GT_RZ = 22,
  GT_HIDE_TURTLE = 23,
  GT_SHOW_TURTLE = 24,
  GT_PEN_UP = 25,
  GT_PEN_DOWN = 26,
  GT_THICKNESS = 27,
  GT_FILL = 28,
  GT_PVH = 29,
  GT_PVB = 30,
  GT_PVG = 31,
  GT_PVD = 32,
  GT_VISE = 33,
  GT_TLP = 34,
  GT_BOUSSOLE = 35,
  GT_MIMIC = 36,
  GT_MIRROR = 37,
  GT_PVXY = 38,
  GT_PVXZ = 39,
  GT_PVYZ = 40,
  GT_WRITE = 41,
  GT_SAY = 42,
  GT_SNAPSHOT = 43,
  GT_PAUSE = 44,
  GT_RETURN = 45,
  GT_STOP = 46,
  GT_WAIT = 47,
  GT_CIRCLE = 48,
  GT_ARC = 49,
  GT_POINT = 50,
  GT_GLOBAL = 51,
  GT_EFF = 52,
  GT_INIT = 53,
  GT_AFF = 54,
  GT_MG = 55,
  GT_PLAY = 56,
  GT_SCORE = 57,
  GT_CONCERT = 58,
  GT_EXECUTE = 59,
  GT_UNDO = 60,
  GT_PEN_COLOR = 61,
  GT_ASSIGN = 62,
  GT_LBRACKET = 63,
  GT_RBRACKET = 64,
  GT_LPAREN = 65,
  GT_RPAREN = 66,
  GT_COMMA = 67,
  GT_SEMICOLON = 68,
  GT_COLON = 69,
  GT_PLUS = 70,
  GT_MINUS = 71,
  GT_MULT = 72,
  GT_DIV = 73,
  GT_POW = 74,
  GT_EQ = 75,
  GT_NEQ = 76,
  GT_LT = 77,
  GT_LTE = 78,
  GT_GT = 79,
  GT_GTE = 80,
  GT_NUMBER = 81,
  GT_STRING = 82,
  GT_ID = 83,
  GT_WORD = 84,
  GT_COMMENT = 85,
  GT_BLOCK_COMMENT = 86,
  GT_WS = 87
}

/**
 * Union type of all token names (e.g. 'GT_REP' | 'GT_WHILE')
 * Useful for logging or string-based logic.
 */
export type GTNTokenName = keyof typeof GTNToken;

/**
 * Union type of all token numeric IDs (e.g. 1 | 2 | 3)
 * Useful for strict ID checking.
 */
export type GTNTokenId = GTNToken;

/**
 * Type Guard: Checks if a string is a valid GTNTokenName.
 * * Usage:
 * if (isGTNTokenName(myString)) {
 * ---> myString is now typed as 'GTNTokenName'
 * }
 */
export function isGTNTokenName(value: unknown): value is GTNTokenName {
  return (
    typeof value === 'string' &&
    value in GTNToken &&
    // Check that the value maps to a Number (the ID).
    // This excludes the reverse mappings (e.g., "1" -> "GT_REP") that exist in numeric enums.
    typeof GTNToken[value as keyof typeof GTNToken] === 'number'
  );
}

/**
 * Assertion Function: Throws an error if the string is not a valid GTNTokenName.
 * * Usage:
 * assertGTNTokenName(myString);
 * ---> code continues only if valid, and myString is typed as 'GTNTokenName'
 */
export function assertGTNTokenName(value: unknown): asserts value is GTNTokenName {
  if (!isGTNTokenName(value)) {
    throw new Error(`Value "${String(value)}" is not a valid GTNTokenName.`);
  }
}

/**
 * Converter: safely casts a string to GTNTokenName.
 * Throws if the value is invalid.
 */
export function toGTNTokenName(value: string): GTNTokenName {
  assertGTNTokenName(value);
  return value;
}

// --- STATIC LITERAL MAPPING ---
// This map is statically generated to decouple the Domain layer from the ANTLR Infrastructure.
const LITERAL_NAMES: Record<number, string> = {
  [GTNToken.GT_REP]: `GT_REP`,
  [GTNToken.GT_WHILE]: `GT_WHILE`,
  [GTNToken.GT_IF]: `GT_IF`,
  [GTNToken.GT_THEN]: `GT_THEN`,
  [GTNToken.GT_ELSE]: `GT_ELSE`,
  [GTNToken.GT_FOR_EACH]: `GT_FOR_EACH`,
  [GTNToken.GT_FROM]: `GT_FROM`,
  [GTNToken.GT_TO]: `GT_TO`,
  [GTNToken.GT_IN_LIST]: `GT_IN_LIST`,
  [GTNToken.GT_FUN]: `GT_FUN`,
  [GTNToken.GT_ASK_FOR]: `GT_ASK_FOR`,
  [GTNToken.GT_ALL]: `GT_ALL`,
  [GTNToken.GT_ASSIGN_KEY]: `GT_ASSIGN_KEY`,
  [GTNToken.GT_RESTE]: `GT_RESTE`,
  [GTNToken.GT_BINOM]: `GT_BINOM`,
  [GTNToken.GT_ALEA]: `GT_ALEA`,
  [GTNToken.GT_FORWARD]: `GT_FORWARD`,
  [GTNToken.GT_BACKWARD]: `GT_BACKWARD`,
  [GTNToken.GT_RIGHT]: `GT_RIGHT`,
  [GTNToken.GT_LEFT]: `GT_LEFT`,
  [GTNToken.GT_VG]: `GT_VG`,
  [GTNToken.GT_RZ]: `GT_RZ`,
  [GTNToken.GT_HIDE_TURTLE]: `GT_HIDE_TURTLE`,
  [GTNToken.GT_SHOW_TURTLE]: `GT_SHOW_TURTLE`,
  [GTNToken.GT_PEN_UP]: `GT_PEN_UP`,
  [GTNToken.GT_PEN_DOWN]: `GT_PEN_DOWN`,
  [GTNToken.GT_THICKNESS]: `GT_THICKNESS`,
  [GTNToken.GT_FILL]: `GT_FILL`,
  [GTNToken.GT_PVH]: `GT_PVH`,
  [GTNToken.GT_PVB]: `GT_PVB`,
  [GTNToken.GT_PVG]: `GT_PVG`,
  [GTNToken.GT_PVD]: `GT_PVD`,
  [GTNToken.GT_VISE]: `GT_VISE`,
  [GTNToken.GT_TLP]: `GT_TLP`,
  [GTNToken.GT_BOUSSOLE]: `GT_BOUSSOLE`,
  [GTNToken.GT_MIMIC]: `GT_MIMIC`,
  [GTNToken.GT_MIRROR]: `GT_MIRROR`,
  [GTNToken.GT_PVXY]: `GT_PVXY`,
  [GTNToken.GT_PVXZ]: `GT_PVXZ`,
  [GTNToken.GT_PVYZ]: `GT_PVYZ`,
  [GTNToken.GT_WRITE]: `GT_WRITE`,
  [GTNToken.GT_SAY]: `GT_SAY`,
  [GTNToken.GT_SNAPSHOT]: `GT_SNAPSHOT`,
  [GTNToken.GT_PAUSE]: `GT_PAUSE`,
  [GTNToken.GT_RETURN]: `GT_RETURN`,
  [GTNToken.GT_STOP]: `GT_STOP`,
  [GTNToken.GT_WAIT]: `GT_WAIT`,
  [GTNToken.GT_CIRCLE]: `GT_CIRCLE`,
  [GTNToken.GT_ARC]: `GT_ARC`,
  [GTNToken.GT_POINT]: `GT_POINT`,
  [GTNToken.GT_GLOBAL]: `GT_GLOBAL`,
  [GTNToken.GT_EFF]: `GT_EFF`,
  [GTNToken.GT_INIT]: `GT_INIT`,
  [GTNToken.GT_AFF]: `GT_AFF`,
  [GTNToken.GT_MG]: `GT_MG`,
  [GTNToken.GT_PLAY]: `GT_PLAY`,
  [GTNToken.GT_SCORE]: `GT_SCORE`,
  [GTNToken.GT_CONCERT]: `GT_CONCERT`,
  [GTNToken.GT_EXECUTE]: `GT_EXECUTE`,
  [GTNToken.GT_UNDO]: `GT_UNDO`,
  [GTNToken.GT_PEN_COLOR]: `GT_PEN_COLOR`,
  [GTNToken.GT_ASSIGN]: `:=`,
  [GTNToken.GT_LBRACKET]: `[`,
  [GTNToken.GT_RBRACKET]: `]`,
  [GTNToken.GT_LPAREN]: `(`,
  [GTNToken.GT_RPAREN]: `)`,
  [GTNToken.GT_COMMA]: `,`,
  [GTNToken.GT_SEMICOLON]: `;`,
  [GTNToken.GT_COLON]: `:`,
  [GTNToken.GT_PLUS]: `+`,
  [GTNToken.GT_MINUS]: `-`,
  [GTNToken.GT_MULT]: `*`,
  [GTNToken.GT_DIV]: `/`,
  [GTNToken.GT_POW]: `^`,
  [GTNToken.GT_EQ]: `=`,
  [GTNToken.GT_NEQ]: `!=`,
  [GTNToken.GT_LT]: `<`,
  [GTNToken.GT_LTE]: `<=`,
  [GTNToken.GT_GT]: `>`,
  [GTNToken.GT_GTE]: `>=`
};

/**
 * Gets the raw literal string associated with a token (e.g., ';' for GT_SEMICOLON)
 */
export function getLiteralName(token: GTNToken): string | undefined {
  return LITERAL_NAMES[token];
}
