/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/generate-antlr-token-enum.ts using GeoTortueParser and GeoTortueLexer
 *
 * Note: This auto-generated file is intentionally tracked by Git. Do not add it to .gitignore.
 */

export enum GTNToken {
  GT_FORWARD = 1,
  GT_BACKWARD = 2,
  GT_TURN_RIGHT = 3,
  GT_TURN_LEFT = 4,
  GT_CLEAR_GRAPHICS = 5,
  GT_RESET = 6,
  GT_UNDO_DRAWING = 7,
  GT_HIDE_TURTLE = 8,
  GT_SHOW_TURTLE = 9,
  GT_PEN_UP = 10,
  GT_PEN_DOWN = 11,
  GT_PEN_COLOR = 12,
  GT_PEN_THICKNESS = 13,
  GT_DRAW_POINT = 14,
  GT_MIRROR = 15,
  GT_TELEPORT = 16,
  GT_COMPASS = 17,
  GT_AIM = 18,
  GT_MIMIC = 19,
  GT_ROTATE_RIGHT = 20,
  GT_ROTATE_LEFT = 21,
  GT_ROTATE_UP = 22,
  GT_ROTATE_DOWN = 23,
  GT_ROTATE_XY = 24,
  GT_ROTATE_XZ = 25,
  GT_ROTATE_YZ = 26,
  GT_DRAW_CIRCLE = 27,
  GT_DRAW_ARC = 28,
  GT_PLAY = 29,
  GT_SCORE = 30,
  GT_CONCERT = 31,
  GT_FILL = 32,
  GT_WRITE = 33,
  GT_SAY = 34,
  GT_INIT = 35,
  GT_WAIT = 36,
  GT_PAUSE = 37,
  GT_STOP = 38,
  GT_RETURN = 39,
  GT_MANIPULATE_GRAPH = 40,
  GT_SNAPSHOT = 41,
  GT_EXECUTE = 42,
  GT_DELETE = 43,
  GT_GLOBAL = 44,
  GT_DISPLAY = 45,
  GT_WRAP = 46,
  GT_WINDOW = 47,
  GT_FENCE = 48,
  GT_REPEAT = 49,
  GT_WHILE = 50,
  GT_FOR_EACH = 51,
  GT_FROM = 52,
  GT_TO = 53,
  GT_IN_LIST = 54,
  GT_IF = 55,
  GT_THEN = 56,
  GT_ELSE = 57,
  GT_SELECT = 58,
  GT_FUNCTION_DEF = 59,
  GT_ASK_FOR_VALUE = 60,
  GT_PROCEDURE_START = 61,
  GT_PROCEDURE_END = 62,
  GT_IDENTIFIER = 63,
  GT_WORD = 64,
  GT_INTEGER_LITERAL = 65,
  GT_FLOATING_POINT_LITERAL = 66,
  GT_STRING_LITERAL = 67,
  GT_STATEMENT_SEPARATOR = 68,
  GT_ASSIGN = 69,
  GT_COMMA = 70,
  GT_LEFT_SQUARE_BRACKET = 71,
  GT_RIGHT_SQUARE_BRACKET = 72,
  GT_LEFT_PARENTHESIS = 73,
  GT_RIGHT_PARENTHESIS = 74,
  GT_COLON = 75,
  GT_GREATER_THAN = 76,
  GT_LESS_THAN = 77,
  GT_EQUAL = 78,
  GT_LESS_OR_EQUAL = 79,
  GT_GREATER_OR_EQUAL = 80,
  GT_NOT_EQUAL = 81,
  GT_LOGICAL_AND = 82,
  GT_LOGICAL_OR = 83,
  GT_PLUS = 84,
  GT_MINUS = 85,
  GT_MULTIPLY = 86,
  GT_DOT = 87,
  GT_DIVIDE = 88,
  GT_MODULO = 89,
  GT_LOGICAL_NOT = 90,
  GT_POWER = 91,
  GT_CROSS_PRODUCT = 92,
  GT_NEW_LINE = 93,
  GT_HORIZONTAL_WHITESPACE = 94,
  GT_LINE_COMMENT_HASH = 95,
  GT_LINE_COMMENT_SLASH = 96,
  GT_BLOCK_COMMENT = 97
}

/**
 * Union type of all token names (e.g. 'GT_REP' | 'GT_WHILE')
 * Useful for logging or string-based logic.
 */
export type GTNTokenName = keyof typeof GTNToken;

/**
 * Union type of all token numeric IDs (e.g. 1 | 2 | 3)
 * Useful for strict ID checking.
 */
export type GTNTokenId = GTNToken;

/**
 * Type Guard: Checks if a string is a valid GTNTokenName.
 * * Usage:
 * if (isGTNTokenName(myString)) {
 * ---> myString is now typed as 'GTNTokenName'
 * }
 */
export function isGTNTokenName(value: unknown): value is GTNTokenName {
  return (
    typeof value === 'string' &&
    value in GTNToken &&
    // Check that the value maps to a Number (the ID).
    // This excludes the reverse mappings (e.g., "1" -> "GT_REP") that exist in numeric enums.
    typeof GTNToken[value as keyof typeof GTNToken] === 'number'
  );
}

/**
 * Assertion Function: Throws an error if the string is not a valid GTNTokenName.
 * * Usage:
 * assertGTNTokenName(myString);
 * ---> code continues only if valid, and myString is typed as 'GTNTokenName'
 */
export function assertGTNTokenName(value: unknown): asserts value is GTNTokenName {
  if (!isGTNTokenName(value)) {
    throw new Error(`Value "${String(value)}" is not a valid GTNTokenName.`);
  }
}

/**
 * Converter: safely casts a string to GTNTokenName.
 * Throws if the value is invalid.
 */
export function toGTNTokenName(value: string): GTNTokenName {
  assertGTNTokenName(value);
  return value;
}

// --- STATIC LITERAL MAPPING ---
// This map is statically generated to decouple the Domain layer from the ANTLR Infrastructure.
const LITERAL_NAMES: Record<number, string> = {
  [GTNToken.GT_FORWARD]: `GT_FORWARD`,
  [GTNToken.GT_BACKWARD]: `GT_BACKWARD`,
  [GTNToken.GT_TURN_RIGHT]: `GT_TURN_RIGHT`,
  [GTNToken.GT_TURN_LEFT]: `GT_TURN_LEFT`,
  [GTNToken.GT_CLEAR_GRAPHICS]: `GT_CLEAR_GRAPHICS`,
  [GTNToken.GT_RESET]: `GT_RESET`,
  [GTNToken.GT_UNDO_DRAWING]: `GT_UNDO_DRAWING`,
  [GTNToken.GT_HIDE_TURTLE]: `GT_HIDE_TURTLE`,
  [GTNToken.GT_SHOW_TURTLE]: `GT_SHOW_TURTLE`,
  [GTNToken.GT_PEN_UP]: `GT_PEN_UP`,
  [GTNToken.GT_PEN_DOWN]: `GT_PEN_DOWN`,
  [GTNToken.GT_PEN_COLOR]: `GT_PEN_COLOR`,
  [GTNToken.GT_PEN_THICKNESS]: `GT_PEN_THICKNESS`,
  [GTNToken.GT_DRAW_POINT]: `GT_DRAW_POINT`,
  [GTNToken.GT_MIRROR]: `GT_MIRROR`,
  [GTNToken.GT_TELEPORT]: `GT_TELEPORT`,
  [GTNToken.GT_COMPASS]: `GT_COMPASS`,
  [GTNToken.GT_AIM]: `GT_AIM`,
  [GTNToken.GT_MIMIC]: `GT_MIMIC`,
  [GTNToken.GT_ROTATE_RIGHT]: `GT_ROTATE_RIGHT`,
  [GTNToken.GT_ROTATE_LEFT]: `GT_ROTATE_LEFT`,
  [GTNToken.GT_ROTATE_UP]: `GT_ROTATE_UP`,
  [GTNToken.GT_ROTATE_DOWN]: `GT_ROTATE_DOWN`,
  [GTNToken.GT_ROTATE_XY]: `GT_ROTATE_XY`,
  [GTNToken.GT_ROTATE_XZ]: `GT_ROTATE_XZ`,
  [GTNToken.GT_ROTATE_YZ]: `GT_ROTATE_YZ`,
  [GTNToken.GT_DRAW_CIRCLE]: `GT_DRAW_CIRCLE`,
  [GTNToken.GT_DRAW_ARC]: `GT_DRAW_ARC`,
  [GTNToken.GT_PLAY]: `GT_PLAY`,
  [GTNToken.GT_SCORE]: `GT_SCORE`,
  [GTNToken.GT_CONCERT]: `GT_CONCERT`,
  [GTNToken.GT_FILL]: `GT_FILL`,
  [GTNToken.GT_WRITE]: `GT_WRITE`,
  [GTNToken.GT_SAY]: `GT_SAY`,
  [GTNToken.GT_INIT]: `GT_INIT`,
  [GTNToken.GT_WAIT]: `GT_WAIT`,
  [GTNToken.GT_PAUSE]: `GT_PAUSE`,
  [GTNToken.GT_STOP]: `GT_STOP`,
  [GTNToken.GT_RETURN]: `GT_RETURN`,
  [GTNToken.GT_MANIPULATE_GRAPH]: `GT_MANIPULATE_GRAPH`,
  [GTNToken.GT_SNAPSHOT]: `GT_SNAPSHOT`,
  [GTNToken.GT_EXECUTE]: `GT_EXECUTE`,
  [GTNToken.GT_DELETE]: `GT_DELETE`,
  [GTNToken.GT_GLOBAL]: `GT_GLOBAL`,
  [GTNToken.GT_DISPLAY]: `GT_DISPLAY`,
  [GTNToken.GT_WRAP]: `GT_WRAP`,
  [GTNToken.GT_WINDOW]: `GT_WINDOW`,
  [GTNToken.GT_FENCE]: `GT_FENCE`,
  [GTNToken.GT_REPEAT]: `GT_REPEAT`,
  [GTNToken.GT_WHILE]: `GT_WHILE`,
  [GTNToken.GT_FOR_EACH]: `GT_FOR_EACH`,
  [GTNToken.GT_FROM]: `GT_FROM`,
  [GTNToken.GT_TO]: `GT_TO`,
  [GTNToken.GT_IN_LIST]: `GT_IN_LIST`,
  [GTNToken.GT_IF]: `GT_IF`,
  [GTNToken.GT_THEN]: `GT_THEN`,
  [GTNToken.GT_ELSE]: `GT_ELSE`,
  [GTNToken.GT_SELECT]: `GT_SELECT`,
  [GTNToken.GT_FUNCTION_DEF]: `GT_FUNCTION_DEF`,
  [GTNToken.GT_ASK_FOR_VALUE]: `GT_ASK_FOR_VALUE`,
  [GTNToken.GT_PROCEDURE_START]: `GT_PROCEDURE_START`,
  [GTNToken.GT_PROCEDURE_END]: `GT_PROCEDURE_END`,
  [GTNToken.GT_STATEMENT_SEPARATOR]: `;`,
  [GTNToken.GT_ASSIGN]: `:=`,
  [GTNToken.GT_COMMA]: `,`,
  [GTNToken.GT_LEFT_SQUARE_BRACKET]: `[`,
  [GTNToken.GT_RIGHT_SQUARE_BRACKET]: `]`,
  [GTNToken.GT_LEFT_PARENTHESIS]: `(`,
  [GTNToken.GT_RIGHT_PARENTHESIS]: `)`,
  [GTNToken.GT_COLON]: `:`,
  [GTNToken.GT_GREATER_THAN]: `>`,
  [GTNToken.GT_LESS_THAN]: `<`,
  [GTNToken.GT_EQUAL]: `=`,
  [GTNToken.GT_LESS_OR_EQUAL]: `<=`,
  [GTNToken.GT_GREATER_OR_EQUAL]: `>=`,
  [GTNToken.GT_NOT_EQUAL]: `!=`,
  [GTNToken.GT_LOGICAL_AND]: `&&`,
  [GTNToken.GT_LOGICAL_OR]: `||`,
  [GTNToken.GT_PLUS]: `+`,
  [GTNToken.GT_MINUS]: `-`,
  [GTNToken.GT_MULTIPLY]: `*`,
  [GTNToken.GT_DOT]: `.`,
  [GTNToken.GT_DIVIDE]: `/`,
  [GTNToken.GT_MODULO]: `%`,
  [GTNToken.GT_LOGICAL_NOT]: `!`,
  [GTNToken.GT_POWER]: `^`,
  [GTNToken.GT_CROSS_PRODUCT]: `^^`
};

/**
 * Gets the raw literal string associated with a token (e.g., ';' for GT_SEMICOLON)
 */
export function getLiteralName(token: GTNToken): string | undefined {
  return LITERAL_NAMES[token];
}
