// The natural language lexemes are provided in files src/assets/locales/{language code}/dsl.json

// Note: The grammar below is mainly extracted from GéoTortue Legacy using ChapGPT Codex
// merging both the jep grammar (extracted from Generated By: JJTree&JavaCC)
// and the GéoTortue grammar (extracted from handwritten parser architecture in geotortue.core - scope parsing, command bundles, command factory, processor)

lexer grammar GeoTortueLexer;

options {
  superClass = antlr.Lexer;
}

// ==========================================
// TURTLE COMMANDS (Canonical English Forms)
// ==========================================

GT_FORWARD                  : 'GT_FORWARD'                  ; // original: av (avancer)
GT_BACKWARD                 : 'GT_BACKWARD'                 ; // original: re (reculer)
GT_TURN_RIGHT               : 'GT_TURN_RIGHT'               ; // original: td (tourner droite)
GT_TURN_LEFT                : 'GT_TURN_LEFT'                ; // original: tg (tourner gauche)
GT_CLEAR_GRAPHICS           : 'GT_CLEAR_GRAPHICS'           ; // original: vg (vide graphique, efface le parcours de toutes les tortues et les repositionne à l'origine.)
GT_RESET                    : 'GT_RESET'                    ; // original: rz (remise a zero, alias de rz)
GT_UNDO_DRAWING             : 'GT_UNDO_DRAWING'             ; // original: UNDO - gomme (annuler le dernier tracé)
GT_HIDE_TURTLE              : 'GT_HIDE_TURTLE'              ; // original: ct (cacher tortue)
GT_SHOW_TURTLE              : 'GT_SHOW_TURTLE'              ; // original: mt (montrer tortue)
GT_PEN_UP                   : 'GT_PEN_UP'                   ; // original: lc (lever crayon)
GT_PEN_DOWN                 : 'GT_PEN_DOWN'                 ; // original: bc (baisser crayon)
GT_PEN_COLOR                : 'GT_PEN_COLOR'                ; // original: crayon (choisir la couleur du crayon)
GT_PEN_THICKNESS            : 'GT_PEN_THICKNESS'            ; // original: THICKNESS - mine (choisir l'épaisseur du crayon)
GT_DRAW_POINT               : 'GT_DRAW_POINT'               ; // original: point (dessiner un point)
GT_MIRROR                   : 'GT_MIRROR'                   ; // original: miroir (inverser la gauche et la droite)
GT_TELEPORT                 : 'GT_TELEPORT'                 ; // original: tlp (téléporter)
GT_COMPASS                  : 'GT_COMPASS'                  ; // original: boussole (utiliser la boussole, soit orienter une tortue vers le nord)
GT_AIM                      : 'GT_AIM'                      ; // original: vise (viser une tortue)
GT_MIMIC                    : 'GT_MIMIC'                    ; // original: imite (imiter une tortue)
GT_ROTATE_RIGHT             : 'GT_ROTATE_RIGHT'             ; // original: pvd (pivoter sur la droite)
GT_ROTATE_LEFT              : 'GT_ROTATE_LEFT'              ; // original: pvg (pivoter sur la gauche)
GT_ROTATE_UP                : 'GT_ROTATE_UP'                ; // original: pvh (pivoter vers le haut)
GT_ROTATE_DOWN              : 'GT_ROTATE_DOWN'              ; // original: pvb (pivoter vers le bas)
GT_ROTATE_XY                : 'GT_ROTATE_XY'                ; // original: pvxy (pivoter autour du plan xy)
GT_ROTATE_XZ                : 'GT_ROTATE_XZ'                ; // original: pvxz (pivoter autour du plan xz)
GT_ROTATE_YZ                : 'GT_ROTATE_YZ'                ; // original: pvyz (pivoter autour du plan yz)
GT_DRAW_CIRCLE              : 'GT_DRAW_CIRCLE'              ; // original: cercle (dessiner un cercle)
GT_DRAW_ARC                 : 'GT_DRAW_ARC'                 ; // original: arc (dessiner un arc)
GT_PLAY                     : 'GT_PLAY'                     ; // original: PLAY - chante (jouer un morceau)
GT_SCORE                    : 'GT_SCORE'                    ; // original: SCORE - partition (assigner une partition)
GT_CONCERT                  : 'GT_CONCERT'                  ; // original: concert (jouer un concert)
GT_FILL                     : 'GT_FILL'                     ; // original: remplis (remplir un polygone)
GT_WRITE                    : 'GT_WRITE'                    ; // original: ECRIS - écris (afficher un texte là où se trouve une tortue)
GT_SAY                      : 'GT_SAY'                      ; // original: dis (afficher un texte dans une fenêtre)
GT_INIT                     : 'GT_INIT'                     ; // original: init (effacer toutes les variables et fonctions utilisateur ; rétablir les fonctions et constantes usuelles)
GT_WAIT                     : 'GT_WAIT'                     ; // original: WAIT - attends (interrompre la tortue)
GT_PAUSE                    : 'GT_PAUSE'                    ; // original: pause (interrompre tout processus en cours pour la durée indiquée)
GT_STOP                     : 'GT_STOP'                     ; // original: stop (sortir de la procédure en cours)
GT_RETURN                   : 'GT_RETURN'                   ; // original: retourne (renvoyer un nombre en sortie de procédure)
GT_MANIPULATE_GRAPH         : 'GT_MANIPULATE_GRAPH'         ; // original: mg (manipuler graphique)
GT_SNAPSHOT                 : 'GT_SNAPSHOT'                 ; // original: photo (enregistre une image de l'espace graphique au format PNG)
GT_EXECUTE                  : 'GT_EXECUTE'                  ; // original: EXECUTE - exec (exécuter des commandes)
GT_DELETE                   : 'GT_DELETE'                   ; // original: eff (supprimer des variables ou fonctions)
GT_GLOBAL                   : 'GT_GLOBAL'                   ; // original: global (déclare une varible global)
GT_DISPLAY                  : 'GT_DISPLAY'                  ; // original: aff (afficher une valeur)

// ==========================================
// KEYWORDS & STRUCTURE (Canonical English Forms)
// ==========================================

GT_REPEAT                   : 'GT_REPEAT'                   ; // original: rep (répéter un même bloc de commande)
GT_WHILE                    : 'GT_WHILE'                    ; // original: tant_que (boucle conditionnelle)
GT_FOR_EACH                 : 'GT_FOR_EACH'                 ; // original: FOR_EACH - pour_chaque, (boucle incrémentielle), alias "boucle" depuis la version 4
GT_FROM                     : 'GT_FROM'                     ; // original: de (boucle incrémentielle : boucle i de 1 à 10)
GT_TO                       : 'GT_TO'                       ; // original: à (boucle incrémentielle :  boucle i de 1 à 10)
GT_IN_LIST                  : 'GT_IN_LIST'                  ; // original: in_list (boucle incrémentielle : pour_chaque el dans L), alias "dans"
GT_IF                       : 'GT_IF'                       ; // original: si (branchement conditionnel)
GT_THEN                     : 'GT_THEN'                     ; // original: alors (branchement conditionnel)
GT_ELSE                     : 'GT_ELSE'                     ; // original: sinon (branchement conditionnel)
GT_SELECT                   : 'GT_SELECT'                   ; // original: SELECT - à (sélectionner une ou plusieurs tortues), now "avec"
GT_FUNCTION_DEF             : 'GT_FUNCTION_DEF'             ; // original: FUN - function (définir une fonction)
GT_ASK_FOR_VALUE            : 'GT_ASK_FOR_VALUE'            ; // original: ASK_FOR - demande_la_valeur_de (demander à l'utilisateur de saisir une valeur)
GT_PROCEDURE_START          : 'GT_PROCEDURE_START'          ; // original: pour (débuter une définition de procédure)
GT_PROCEDURE_END            : 'GT_PROCEDURE_END'            ; // original: fin (terminer une définition de procédure)

// ==========================================
// IDENTIFIERS, NUMBERS, STRINGS
// ==========================================

// TODO do we really need to create var name with dot inside.
// TODO both GT_IDENTIFIER and GT_WORD?

// --- Identifiers (Strict ASCII for internal vars, Extended for commands matching) ---

GT_IDENTIFIER               : GT_SIMPLE_ID_FRAGMENT (GT_SIMPLE_ID_FRAGMENT | GT_DECIMAL_DIGIT)* ;

// Extended word for accented commands (like écris)
// If it matches ID, ID takes precedence if listed first? No, ANTLR matches longest.
// If same length, first rule wins. We put GT_IDENTIFIER first.
// Any command that fails GT_IDENTIFIER (accents) will be GT_WORD.
GT_WORD                     : GT_IDENTIFIER_START_FRAGMENT (GT_IDENTIFIER_PART_FRAGMENT | '.')* ; // original: IDENTIFIER

// Expression literals
GT_INTEGER_LITERAL          : GT_DECIMAL_DIGITS_FRAGMENT                                 ; // original: INTEGER_LITERAL
GT_FLOATING_POINT_LITERAL
                            : GT_DECIMAL_DIGITS_FRAGMENT '.' GT_DECIMAL_DIGITS_FRAGMENT? GT_EXPONENT_PART_FRAGMENT?
                            | '.' GT_DECIMAL_DIGITS_FRAGMENT GT_EXPONENT_PART_FRAGMENT?
                            | GT_DECIMAL_DIGITS_FRAGMENT GT_EXPONENT_PART_FRAGMENT
                            ; // original: FLOATING_POINT_LITERAL
GT_STRING_LITERAL           : '"' ( ~["\\\n\r] | '\\' [ntbrf\\'"] )* '"'          ; // original: STRING_LITERAL

// ==========================================
// OPERATORS & SYMBOLS
// ==========================================

// --- Symbols ---
GT_STATEMENT_SEPARATOR      : ';'                           ; // original: ';'
GT_ASSIGN                   : ':='                          ; // original: = in JEP, := in Géotortue
GT_COMMA                    : ','                           ; // original: ,
GT_LEFT_SQUARE_BRACKET      : '['                           ; // original: [
GT_RIGHT_SQUARE_BRACKET     : ']'                           ; // original: ]
GT_LEFT_PARENTHESIS         : '('                           ; // original: (
GT_RIGHT_PARENTHESIS        : ')'                           ; // original: )
GT_COLON                    : ':'                           ; // original: :

// --- Math Operators ---
GT_GREATER_THAN             : '>'                           ; // original: >
GT_LESS_THAN                : '<'                           ; // original: <
GT_EQUAL                    : '='                           ; // original: == in JEP, = in GéoTortue
GT_LESS_OR_EQUAL            : '<='                          ; // original: <=
GT_GREATER_OR_EQUAL         : '>='                          ; // original: >=
GT_NOT_EQUAL                : '!='                          ; // original: !=
GT_LOGICAL_AND              : '&&'                          ; // original: &&
GT_LOGICAL_OR               : '||'                          ; // original: ||
GT_PLUS                     : '+'                           ; // original: +
GT_MINUS                    : '-'                           ; // original: -
GT_MULTIPLY                 : '*'                           ; // original: *
GT_DOT                      : '.'                           ; // original: .
GT_DIVIDE                   : '/'                           ; // original: /
GT_MODULO                   : '%'                           ; // original: %
GT_LOGICAL_NOT              : '!'                           ; // original: !
GT_POWER                    : '^'                           ; // original: ^
GT_CROSS_PRODUCT            : '^^'                          ; // original: ^^

// ==========================================
// FRAGMENTS
// ==========================================

fragment GT_DECIMAL_DIGIT   : [0-9];
fragment GT_DECIMAL_DIGITS_FRAGMENT
                            : [0-9]+                        ; // original: DECIMAL_LITERAL
fragment GT_EXPONENT_PART_FRAGMENT
                            : [eE] [+-]? [0-9]+             ; // original: EXPONENT
fragment GT_SIMPLE_ID_FRAGMENT
                            : [A-Z]
                            | '_'
                            | [a-z]
                            ;
fragment GT_IDENTIFIER_START_FRAGMENT
                            : '$'
                            | GT_SIMPLE_ID_FRAGMENT
                            | [\u00C0-\u00D6]
                            | [\u00D8-\u00F6]
                            | [\u00F8-\u00FF]
                            | [\u0100-\u1FFF]
                            | [\u3040-\u318F]
                            | [\u3300-\u337F]
                            | [\u3400-\u3D2D]
                            | [\u4E00-\u9FFF]
                            | [\uF900-\uFAFF]
                            ; // original: LETTER1 / LETTER2
fragment GT_IDENTIFIER_PART_FRAGMENT
                            : GT_IDENTIFIER_START_FRAGMENT
                            | GT_DECIMAL_DIGIT
                            ; // original: DIGIT1 / DIGIT2

// ==========================================
// WHITESPACE & COMMENTS
// ==========================================

GT_NEW_LINE                 : ('\r'? '\n')+                                   ; // original: '\n' / '\r\n'
GT_HORIZONTAL_WHITESPACE    : [ \t\f]+                      -> channel(HIDDEN); // original: horizontal whitespace
GT_LINE_COMMENT_HASH        : '#' ~[\r\n]*                  -> channel(HIDDEN); // original: #...
GT_LINE_COMMENT_SLASH       : '//' ~[\r\n]*                 -> channel(HIDDEN); // original: //...
GT_BLOCK_COMMENT            : '/*' .*? '*/'                 -> channel(HIDDEN); // original: /*...*/
