// GTNSyntaxService.getTokenStyleMap (src/domain/services/) is used to highlight the tokens in the IDE editor.
// It must be manually updated after any addition or suppression of **rules**, i.e.:
// - automatic mapping for primitive, structure or expr and also repeatBlock, whileBlock, ifBlock, forEachBlock, forEachBlock
// - but also manuel mapping such as number, string, id, comment, etc.

// Two scripts are launched after each run of antlr-ng:
// - scripts/generate-antlr-token-enum.ts to create GTNToken.ts (src/domain/types/)
// - scripts/generate-command-arities.ts to create GTNCommandArity.ts (src/domain/types/)

// Some fixes must be applied on generated files as ANTRL4 ignores type-only import syntax (since TS 3.8).
// See e.g. ParseTreeListener as a type
// A dedicated script scripts/fix-antlr-types-generated.ts is executed after each ANTRL4 run.

// Note: The grammar below is mainly extracted from GéoTortue Legacy using ChapGPT Codex
// merging both the jep grammar (extracted from Generated By: JJTree&JavaCC)
// and the GéoTortue grammar (extracted from handwritten parser architecture in geotortue.core - scope parsing, command bundles, command factory, processor)

parser grammar GeoTortueParser;

options {
  tokenVocab = GeoTortueLexer;
  superClass = antlr.Parser;
}

program
    : terminator* (statement terminator*)* EOF
    ;

statement
    : procedureDefinition                             # ProcedureDef
    | structureStatement
    | commandStatement
    | procedureCallStatement                          # ProcedureCall
    | expressionStatement
    ;

procedureDefinition
    : terminator* GT_PROCEDURE_START GT_IDENTIFIER procedureParameter* terminator*
      procedureBody
      GT_PROCEDURE_END
    ;

procedureParameter
    : GT_IDENTIFIER
    ;

procedureBody
    : (statement terminator*)*
    ;

commandStatement
    : fixedArityZeroCommandStatement
    | fixedArityOneCommandStatement
    | fixedArityTwoCommandStatement
    | variableArityMarkerCommandStatement
    ;

fixedArityZeroCommandStatement
    : GT_CLEAR_GRAPHICS                               # ClearGraphics
    | GT_RESET                                        # Reset
    | GT_HIDE_TURTLE                                  # HideTurtle
    | GT_SHOW_TURTLE                                  # ShowTurtle
    | GT_PEN_UP                                       # PenUp
    | GT_PEN_DOWN                                     # PenDown
    | GT_COMPASS                                      # Compass
    | GT_INIT                                         # Init
    | GT_WAIT                                         # Wait
    | GT_STOP                                         # Stop
    | GT_UNDO_DRAWING                                 # UndoDrawing
    | GT_DRAW_POINT                                   # DrawPoint
    | GT_MIRROR                                       # Mirror
    ;

fixedArityOneCommandStatement
    : GT_FORWARD commandArgument                      # MoveForward
    | GT_BACKWARD commandArgument                     # MoveBackward
    | GT_TURN_RIGHT commandArgument                   # TurnRight
    | GT_TURN_LEFT commandArgument                    # TurnLeft
    | GT_PEN_THICKNESS commandArgument                # PenThickness
    | GT_PEN_COLOR commandArgument                    # PenColor
    | GT_AIM commandArgument                          # Aim
    | GT_MIMIC commandArgument                        # Mimic
    | GT_PAUSE commandArgument                        # Pause
    | GT_ROLL_UP commandArgument                      # RollUp
    | GT_ROLL_DOWN commandArgument                    # RollDown
    | GT_ROLL_RIGHT commandArgument                   # RollRight
    | GT_ROLL_LEFT commandArgument                    # RollLeft
    | GT_ROTATE_XY commandArgument                    # RotateXY
    | GT_ROTATE_XZ commandArgument                    # RotateXZ
    | GT_ROTATE_YZ commandArgument                    # RotateYZ
    | GT_SNAPSHOT commandArgument                     # Snapshot
    | GT_RETURN commandArgument                       # Return
    | GT_DRAW_CIRCLE commandArgument                  # DrawCircle
    | GT_FILL commandArgument                         # Fill
    | GT_MANIPULATE_GRAPH commandArgument             # ManipulateGraph
    ;

fixedArityTwoCommandStatement
    : GT_DRAW_ARC commandArgument commandArgument     # DrawArc
    ;

variableArityMarkerCommandStatement
    : GT_TELEPORT commandArgument*                    # Teleport
    | GT_SELECT commandArgument*                      # Select
    | GT_DELETE commandArgument*                      # Delete
    | GT_DISPLAY commandArgument*                     # Display
    | GT_WRITE commandArgument*                       # Write
    | GT_SAY commandArgument*                         # Say
    | GT_EXECUTE commandArgument*                     # Execute
    | GT_PLAY commandArgument*                        # PlayMusic
    | GT_SCORE commandArgument*                       # Score
    | GT_CONCERT commandArgument*                     # Concert
    | GT_ASK_FOR_VALUE commandArgument*               # AskForValue
    | GT_GLOBAL commandArgument*                      # Global
    ;

structureStatement
    : repeatBlock
    | whileBlock
    | ifBlock
    | forEachBlock
    | functionDef
    ;

repeatBlock
    : GT_REPEAT expression commandBlock
    ;

whileBlock
    : GT_WHILE expression commandBlock
    ;

ifBlock
    : GT_IF expression GT_THEN? commandBlock (GT_ELSE commandBlock)?
    ;

forEachBlock
    : GT_FOR_EACH GT_IDENTIFIER GT_IN_LIST expression commandBlock
    | GT_FOR_EACH GT_IDENTIFIER GT_FROM expression GT_TO expression commandBlock
    ;

functionDef
    : GT_FUNCTION_DEF GT_IDENTIFIER GT_LEFT_PARENTHESIS (GT_IDENTIFIER (GT_COMMA GT_IDENTIFIER)*)? GT_RIGHT_PARENTHESIS GT_ASSIGN expression
    ;

procedureCallStatement
    : GT_IDENTIFIER commandArgument*
    ;

commandArgument
    : commandBlock
    | expression
    ;

commandBlock
    : GT_LEFT_SQUARE_BRACKET terminator* (statement terminator*)* GT_RIGHT_SQUARE_BRACKET
    ;

expressionStatement
    : expression
    ;

expression
    : assignExpression                  # VarAssignment
    | rightExpression
    ;

assignExpression
    : lValue GT_ASSIGN expression
    ;

rightExpression
    : logicalOrExpression
    ;

logicalOrExpression
    : logicalAndExpression (GT_LOGICAL_OR logicalAndExpression)*
    ;

logicalAndExpression
    : equalityExpression (GT_LOGICAL_AND equalityExpression)*
    ;

equalityExpression
    : relationalExpression ((GT_NOT_EQUAL | GT_EQUAL) relationalExpression)*
    ;

relationalExpression
    : additiveExpression ((GT_LESS_THAN | GT_GREATER_THAN | GT_LESS_OR_EQUAL | GT_GREATER_OR_EQUAL) additiveExpression)*
    ;

additiveExpression
    : multiplicativeExpression ((GT_PLUS | GT_MINUS) multiplicativeExpression)*
    ;

multiplicativeExpression
    : unaryExpression ((GT_MULTIPLY | GT_DOT | GT_CROSS_PRODUCT | GT_DIVIDE | GT_MODULO) unaryExpression | powerExpression)*
    ;

unaryExpression
    : GT_PLUS unaryExpression
    | GT_MINUS unaryExpression
    | GT_LOGICAL_NOT unaryExpression
    | powerExpression
    ;

powerExpression
    : unaryExpressionWithoutSign (GT_POWER unaryExpression)?
    ;

unaryExpressionWithoutSign
    : constant
    | arrayAccess
    | functionCall
    | variable
    | GT_LEFT_PARENTHESIS expression GT_RIGHT_PARENTHESIS
    | listLiteral
    ;

listLiteral
    : GT_LEFT_SQUARE_BRACKET expression (GT_COMMA expression)* GT_RIGHT_SQUARE_BRACKET
    ;

lValue
    : arrayAccess
    | variable
    ;

arrayAccess
    : variable listLiteral
    ;

variable
    : GT_IDENTIFIER
    ;

functionCall
    : GT_IDENTIFIER GT_LEFT_PARENTHESIS argumentList GT_RIGHT_PARENTHESIS
    ;

argumentList
    : (expression (GT_COMMA expression)*)?
    ;

// TODO define color constants
constant
    : GT_STRING_LITERAL
    | GT_INTEGER_LITERAL
    | GT_FLOATING_POINT_LITERAL
    ;

terminator
    : (GT_STATEMENT_SEPARATOR | GT_NEW_LINE)+
    ;
