import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

type Arity = {
  min: number;
  max?: number;
};

const __dirname = dirname(fileURLToPath(import.meta.url));
const PARSER_GRAMMAR_PATH = resolve(
  __dirname,
  '../src/infrastructure/antlr/grammar/GeoTortueParser.g4'
);
const OUTPUT_PATH = resolve(__dirname, '../src/domain/types/GTNCommandArity.ts');

const grammar = readFileSync(PARSER_GRAMMAR_PATH, 'utf-8');

const primitiveMatch = grammar.match(/\bprimitive\s*\n\s*:\s*([\s\S]*?)\n\s*;/m);
if (!primitiveMatch?.[1]) {
  throw new Error('Unable to locate the primitive rule in GeoTortueParser.g4.');
}

const cleanAlternative = (raw: string): string => {
  return raw
    .replace(/\/\/.*$/gm, '')
    .replace(/#\w+/g, '')
    .replace(/\s+/g, ' ')
    .trim();
};

const alternatives = primitiveMatch[1]
  .split(/\n\s*\|/)
  .map((part, index) => {
    if (index === 0) {
      return part;
    }

    return `| ${part}`;
  })
  .map((part) => part.replace(/^\s*\|\s*/, ''))
  .map(cleanAlternative)
  .filter(Boolean);

const addArity = (arity: Arity, quantifier: string | undefined): Arity => {
  switch (quantifier) {
    case '*':
      return {
        min: arity.min
      };
    case '+':
      return {
        min: arity.min + 1
      };
    case '?':
      return {
        min: arity.min,
        max: arity.max === undefined ? undefined : arity.max + 1
      };
    default:
      return {
        min: arity.min + 1,
        max: arity.max === undefined ? undefined : arity.max + 1
      };
  }
};

const getArity = (ruleBody: string): Arity => {
  const argumentPattern = /\b(expr|block)\b([*+?])?/g;
  let arity: Arity = { min: 0, max: 0 };

  for (const match of ruleBody.matchAll(argumentPattern)) {
    arity = addArity(arity, match[2]);
  }

  return arity;
};

const entries: string[] = [];

for (const alternative of alternatives) {
  const commandToken = alternative.match(/^(GT_[A-Z0-9_]+)/)?.[1];
  if (!commandToken) {
    continue;
  }

  const ruleBody = alternative.replace(new RegExp(`^${commandToken}\\b`), '').trim();
  const arity = getArity(ruleBody);
  const maxPart = arity.max === undefined ? '' : `, max: ${arity.max}`;

  entries.push(`  ${commandToken}: { min: ${arity.min}${maxPart} }`);
}

const output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/generate-command-arities.ts using GeoTortueParser.g4
 *
 * Note: This auto-generated file is intentionally tracked by Git. Do not add it to .gitignore.
 */

/**
 * Arity metadata for a DSL command.
 * - min: minimal number of arguments.
 * - max: maximal number of arguments. If omitted, the command is variadic.
 */
export type GTNCommandArity = {
  min: number;
  max?: number;
};

/**
 * Command arities for primitive DSL commands.
 */
export const GTN_COMMAND_ARITIES: Readonly<Record<string, GTNCommandArity>> = {
${entries.join(',\n')}
};
`;

writeFileSync(OUTPUT_PATH, output, 'utf-8');

console.log('✅ Generated command arities table at:');
console.log(`   ${OUTPUT_PATH}`);
