import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// Import BOTH Parser and Lexer strictly for the generation process
import { GeoTortueParser } from '../src/infrastructure/antlr/generated/GeoTortueParser';
import { GeoTortueLexer } from '../src/infrastructure/antlr/generated/GeoTortueLexer';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = resolve(__dirname, '../src/domain/types/GTNToken.ts');

console.log('🔄 Generating GTNToken Enum & Types...');

// Get pairs [Name, ID]
const tokenPairs = GeoTortueParser.symbolicNames
  .map((name, id) => [name, id] as const)
  .filter(([name]) => name != null);

// Format Enum Members
const enumMembers = tokenPairs.map(([name, id]) => `  ${name} = ${id}`);

// Build the static Literal Map (Resolving the "FUTURE" comment)
// ANTLR literal names share the same index (id) as symbolic names.
const literalMapEntries = tokenPairs
  .map(([name, id]) => {
    const rawLiteral = GeoTortueLexer.literalNames[id];
    if (rawLiteral) {
      // ANTLR wraps literals in single quotes (e.g. "';'"). We strip them.
      const cleanLiteral = rawLiteral.replace(/^'(.*)'$/, '$1');
      // Use backticks to safely wrap the literal string
      return `  [GTNToken.${name}]: \`${cleanLiteral}\``;
    }
    return null;
  })
  .filter((entry) => entry !== null);

// Assemble File Content
const fileContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/generate-antlr-token-enum.ts using GeoTortueParser and GeoTortueLexer
 */

export enum GTNToken {
${enumMembers.join(',\n')}
}

/**
 * Union type of all token names (e.g. 'GT_REP' | 'GT_WHILE')
 * Useful for logging or string-based logic.
 */
export type GTNTokenName = keyof typeof GTNToken;

/**
 * Union type of all token numeric IDs (e.g. 1 | 2 | 3)
 * Useful for strict ID checking.
 */
export type GTNTokenId = GTNToken;

/**
 * Type Guard: Checks if a string is a valid GTNTokenName.
 * * Usage:
 * if (isGTNTokenName(myString)) {
 * ---> myString is now typed as 'GTNTokenName'
 * }
 */
export function isGTNTokenName(value: unknown): value is GTNTokenName {
  return (
    typeof value === 'string' &&
    value in GTNToken &&
    // Check that the value maps to a Number (the ID).
    // This excludes the reverse mappings (e.g., "1" -> "GT_REP") that exist in numeric enums.
    typeof GTNToken[value as keyof typeof GTNToken] === 'number'
  );
}

/**
 * Assertion Function: Throws an error if the string is not a valid GTNTokenName.
 * * Usage:
 * assertGTNTokenName(myString);
 * ---> code continues only if valid, and myString is typed as 'GTNTokenName'
 */
export function assertGTNTokenName(value: unknown): asserts value is GTNTokenName {
  if (!isGTNTokenName(value)) {
    throw new Error(\`Value "\${String(value)}" is not a valid GTNTokenName.\`);
  }
}

/**
 * Converter: safely casts a string to GTNTokenName.
 * Throws if the value is invalid.
 */
export function toGTNTokenName(value: string): GTNTokenName {
  assertGTNTokenName(value);
  return value;
}

// --- STATIC LITERAL MAPPING ---
// This map is statically generated to decouple the Domain layer from the ANTLR Infrastructure.
const LITERAL_NAMES: Record<number, string> = {
${literalMapEntries.join(',\n')}
};

/**
 * Gets the raw literal string associated with a token (e.g., ';' for GT_SEMICOLON)
 */
export function getLiteralName(token: GTNToken): string | undefined {
  return LITERAL_NAMES[token];
}
`;

writeFileSync(OUTPUT_PATH, fileContent, 'utf-8');

console.log(`✅ Generated Enum + Types at:`);
console.log(`   ${OUTPUT_PATH}`);
