import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// Import the actual generated parser
import { GeoTortueParser } from '../src/infrastructure/antlr/generated/GeoTortueParser';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = resolve(__dirname, '../src/domain/types/GTNToken.ts');

console.log('🔄 Generating GTNToken Enum & Types...');

// Get pairs [Name, ID]
const tokenPairs = GeoTortueParser.symbolicNames
  .map((name, id) => [name, id] as const)
  .filter(([name]) => name !== null);

// Format Enum Members
const enumMembers = tokenPairs.map(([name, id]) => `  ${name} = ${id}`);

// Assemble File Content
// We use "keyof typeof" to automatically generate the Union Type 'GT_REP' | 'GT_WHILE'
const fileContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/generate-token-enum.ts using GeoTortueParser.symbolicNames
 */

export enum GTNToken {
${enumMembers.join(',\n')}
};

/**
 * Union type of all token names (e.g. 'GT_REP' | 'GT_WHILE')
 * Useful for logging or string-based logic.
 */
export type GTNTokenName = keyof typeof GTNToken;

/**
 * Union type of all token numeric IDs (e.g. 1 | 2 | 3)
 * Useful for strict ID checking.
 */
export type GTNTokenId = GTNToken;
`;

// 4. Write to disk
writeFileSync(OUTPUT_PATH, fileContent, 'utf-8');

console.log(`✅ Generated Enum + Types at:`);
console.log(`   ${OUTPUT_PATH}`);
